### ISSUE TITLE
[WIP] Contao 4 support

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/translator#6]
I'd like to get our cca tools Contao 4 ready in the next months. I would work on it. But let's clarify the decisions which has to be made.

The main question for me is if we want to continue developing our translator libary or can we migrate to the symfony translator in the future.
- [ ] Check what's the current state in Contao 4. Is already support for contao language files and translator included
- [ ] Check if it's possible to combine the symfony translator and cca/translator. How could transChoice and translatePluralized being mapped?

/cc @discordier @stefanheimes

**Comment by discordier** [comment]
Contao 4 does not have a translator service of it's own so far. Long term migration should use the symfony translator of the symfony app.

They can not get merged easily though - therefore our translator will remain for a while as a mitigation.

However, we should move away from it for new extensions - these will not be compatible with both Contao versions then though.

**Comment by dmolineus** [comment]
I'll work on the Contao4 release for the translator for noone has prepared something sofare.

**Comment by discordier** [comment]
AFAIR @baumannsven has something in the pipeline.
The three of us should coordinate the next steps in the upcoming week.

**Comment by baumannsven** [comment]
WIP by me

**Comment by dmolineus** [comment]
I close it in favour of https://github.com/contao-community-alliance/translator/pull/7.
