### ISSUE TITLE
Problems in Contao 4.8

### ISSUE THREAD

**Issue by frontendschlampe** [contao-community-alliance/translator#8]
As discussed with @discordier there's a change in https://github.com/contao/core-bundle/commit/8bd8b0d9bcffcd9bf01370dc68978edbe92ce00f#diff-577cb0589044f854e85f6417f76c39ab that's why the translator is not working in Contao 4.8.

```html
[WARNING] Some commands could not be registered: 

In ImageSizes.php line 56:

Argument 4 passed to Contao\CoreBundle\Image\ImageSizes::__construct() must 
be an instance of Contao\CoreBundle\Translation\Translator, instance of Co 
ntaoCommunityAlliance\Translator\BackportedTranslator given, called in /www 
/htdocs/XXX/dev.domain.de/var/cache/prod/ContainerIniWaRo/ge 
tContao_Image_ImageSizesService.php on line 11
```

**Comment by dmolineus** [comment]
I assume that Contao should use the translator interface instead of the concrete implementation as argument type. 

Do you see any reasons why Contao doesn't, @discordier

**Comment by discordier** [comment]
No I don't and I am with you on this one.

However, we can circumvent this by only registering our alias when it does not exist yet in a compiler pass. I think this is the route we should go as it takes less time than waiting for Contao to fix this.

We should report this upstream to Contao however as others might want to replace the service and end up in the same situation then.

**Comment by dmolineus** [comment]
I'll have a look on it. I don't understand why this happens as we already check if the service is defined.

https://github.com/contao-community-alliance/translator/blob/daa920897510c10ee400b29c83840a866c17623a/src/DependencyInjection/CcaTranslatorExtension.php#L42-L44

**Comment by dmolineus** [comment]
2.1.4 mit entsprechenden Bugfix ist released
